version: '3.7'

services:
  app: 
    build: .
    container_name: mailparser
    volumes: 
      - .:/code
    working_dir: /code
    command: sleep infinity
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_URI=${DB_URI}
  db:
    container_name: hydrodb
    image: postgres:11
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data/
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
volumes:
  postgresdata: